"""Validated schema objects, one module per storage-model layer.

See `system.md` §2 for the storage model these mirror. Cross-cutting enums and
helpers live in `base`.
"""

from src.backend.common.schemas.base import (
    KNOWN_CITATION_TARGETS,
    KNOWN_CLAIM_TYPES,
    KNOWN_GENERATION_TASKS,
    AnalogyUsage,
    CourseEnrollmentRole,
    CourseLifecycleStatus,
    CourseVisibility,
    EnrollmentSource,
    EnrollmentStatus,
    ErrorCategory,
    EvidenceLevel,
    IngestionStage,
    IngestionStatus,
    MasteryState,
    MemoryObjectKind,
    MessageRole,
    ObjectAccessScope,
    PrereqKind,
    ResponseStructure,
    SourcePresentation,
    SourceStatus,
    SourceType,
    TutorVerbosity,
    UserTier,
)
from src.backend.common.schemas.chat import ChatSummary, Conversation, ConversationTurn
from src.backend.common.schemas.evidence import (
    ArchivedCitation,
    ArtifactOrigin,
    Citation,
    CitationSnapshot,
    Claim,
    MemoryObjectEvidence,
    ModelDecision,
    Response,
    RetrievalTrace,
    UserArtifactOrigin,
)
from src.backend.common.schemas.identity import (
    ArchivedCourse,
    Course,
    CourseArchiveAccess,
    CourseEnrollment,
    CourseMemory,
    CourseObject,
    StorageCleanupJob,
    StudyPeriod,
    User,
    UserAccount,
    UserArtifact,
)
from src.backend.common.schemas.ingestion import IngestionRun, IngestionStageRun
from src.backend.common.schemas.memory import (
    Concept,
    Dependency,
    MemoryObject,
    TableOfContents,
    TocEntry,
)
from src.backend.common.schemas.source_content import Chunk, Locator, Source
from src.backend.common.schemas.spend import (
    GenerationLedgerEntry,
    PremiumCode,
    UserSubscription,
)
from src.backend.common.schemas.student_model import (
    AssessmentItem,
    Attempt,
    ConceptMastery,
    Recommendation,
)
from src.backend.common.schemas.tutor import TutorProfile

__all__ = [
    "ArchivedCitation",
    "ArchivedCourse",
    "AnalogyUsage",
    "ArtifactOrigin",
    "AssessmentItem",
    "Attempt",
    "ChatSummary",
    "Chunk",
    "Citation",
    "CitationSnapshot",
    "Claim",
    "Concept",
    "ConceptMastery",
    "Conversation",
    "ConversationTurn",
    "Course",
    "CourseArchiveAccess",
    "CourseEnrollment",
    "CourseEnrollmentRole",
    "CourseLifecycleStatus",
    "CourseVisibility",
    "CourseMemory",
    "CourseObject",
    "Dependency",
    "ErrorCategory",
    "EvidenceLevel",
    "EnrollmentSource",
    "EnrollmentStatus",
    "GenerationLedgerEntry",
    "IngestionRun",
    "IngestionStage",
    "IngestionStageRun",
    "IngestionStatus",
    "KNOWN_CLAIM_TYPES",
    "KNOWN_CITATION_TARGETS",
    "KNOWN_GENERATION_TASKS",
    "Locator",
    "MasteryState",
    "MemoryObject",
    "MemoryObjectEvidence",
    "MemoryObjectKind",
    "MessageRole",
    "ModelDecision",
    "ObjectAccessScope",
    "PrereqKind",
    "PremiumCode",
    "Recommendation",
    "Response",
    "ResponseStructure",
    "RetrievalTrace",
    "Source",
    "SourceStatus",
    "SourcePresentation",
    "SourceType",
    "StudyPeriod",
    "StorageCleanupJob",
    "TableOfContents",
    "TocEntry",
    "TutorProfile",
    "TutorVerbosity",
    "User",
    "UserAccount",
    "UserArtifact",
    "UserArtifactOrigin",
    "UserSubscription",
    "UserTier",
]
